### ISSUE TITLE
Plugin Install Failed

### ISSUE THREAD

**Issue by kael-moreno** [DevDmitryHub/cordova-plugin-appsflyer#4]
Hi,

I'm using XDK to build the app. However, it always says Plugin Install failed. Any solution?

Thanks,

Kael

**Comment by golts** [comment]
try getting the plugin from: 
https://github.com/AppsFlyerSDK/PhoneGap

**Comment by DevDmitryHub** [comment]
@kaelitokael try to use the latest release or an official plugin version by link above.
